
version: "3.9"

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      # KRaft (single-node, broker + controller)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listener per i container e per lâ€™host (doppio listener)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://192.168.178.166:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

      # Parametri minimi per single-node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"   # per altri container
      - "29092:29092" # per tool sul tuo host
    healthcheck:
      test: ["CMD-SHELL", "bash -lc '/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1'"]
      interval: 10s
      timeout: 10s
      retries: 10

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: temperature_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d temperature_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # consumer:
  #   build: ./consumer
  #   container_name: consumer
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/temperature_db
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy

volumes:
  pgdata: {}
